--
-- Name: recipes; Type: TABLE; Schema: public; Owner: postgres; Tablespace: 
--

CREATE TABLE recipes (
    id integer PRIMARY KEY,
    title character varying(100) NOT NULL,
    description character varying(255) NOT NULL,
    content text NOT NULL,
    preparation_endurance integer NOT NULL,
    total_endurance integer NOT NULL,
    creation timestamp without time zone NOT NULL
);


ALTER TABLE public.recipes OWNER TO username;

--
-- Add sequence and user rights for id increment
--
CREATE SEQUENCE hibernate_sequence
  INCREMENT 1
  MAXVALUE 9223372036854775807
  START 100000;
  
grant usage on sequence hibernate_sequence to username;

create table images (
  id		integer primary key,
  path		varchar(255) not null,
  description		varchar(255) not null,
  recipe_id	integer,
  foreign key (recipe_id) references recipes (id)
);

grant select,insert,update,delete on images to username;

--
-- Data for Name: recipes; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY recipes (id, title, description, content, preparation_endurance, total_endurance, creation) FROM stdin;
1	Käse - Lauch - Suppe mit Lachs	schmeckt wonach es klingt	<b>\r\n200 g \tKartoffel(n)<br>\r\n250 g \tPorree<br>\r\n1  \tZwiebel(n)<br>\r\n25 g \tButter<br>\r\n500 ml \tHühnerbrühe<br>\r\n200 g \tSchmelzkäse<br>\r\n100 g \tLachs, geräucherter<br>\r\n4 EL \tCrème fraîche<br>\r\n  \tSalz und Pfeffer <br>\r\n</b><br><br><br>\r\nDie Kartoffeln schälen, waschen und würfeln. Den Porree abbrausen, putzen und in Ringe schneiden. Die Zwiebeln schälen und fein würfeln.<br>\r\n<br>\r\nButter in einem Topf erhitzen und alles darin anbraten. Brühe angießen, kurz aufkochen lassen und bei mittlerer Hitze etwa 20 Minuten köcheln lassen. Die Suppe mit dem Mixstab pürieren. Den Schmelzkäse hineingeben und unter Rühren nochmals erhitzen. Mit Salz und Pfeffer abschmecken.<br>\r\n\r\nDen Lachs in Streifen schneiden. Die Suppe in Tellern anrichten und in die Mitte jeweils einen EL Crème fraîche geben und die Lachsstreifen hinzufügen. 	30	60	2013-12-10 09:20:42.313
0	Kartoffelauflauf	einfacher leckerer Auflauf	<b>500gr Kartoffeln</b><br><br><br>Die Kartoffeln kochen, pellen und in gleichmäßige Scheiben schneiden. Die Auflaufform mit der Knoblauchzehe einreiben und anschließend mit der Butter einfetten. <br>\r\nDen Rest der Zehe in kleine Stücke hacken und zusammen mit den Zwiebelringen in einer Pfanne anbraten. Die Kartoffelscheiben, die Zwiebeln und den Käse abwechselnd aufschichten und mit Salz und Pfeffer nach jeder Schicht würzen. Mit Käse abschließen, Sahne und Kräuter vermengen und über das Gratin geben. Den Auflauf 20-30 Minuten im vorgeheizten Backofen bei 170 Grad überbacken.\r\n<br>\r\nDazu passen Bratwürstchen oder man fügt noch eine Schicht Thunfisch hinzu. Durchgezogen schmeckt das Gratin noch besser. <br>	35	45	2013-12-10 09:15:23.974
2	Echte Gulaschsuppe	herzhafte Gulaschsuppe - ungarisch	<b>\r\n12  \tZwiebel(n)<br>\r\n500 g \tRindfleisch<br>\r\n1 Liter \tFleischbrühe<br>\r\n100 g \tSchweineschmalz<br>\r\n1 EL \tPaprikapulver, scharf<br>\r\n2 EL \tPaprikapulver, edelsüss<br>\r\n1 TL \tKümmel, zerstossen<br>\r\n1/2 TL \tMajoran, gerebbelt<br>\r\n1 TL \tSalz<br>\r\n2  \tKartoffel(n), geschält und gewürfelt<br>\r\n2  \tPaprikaschote(n), grün, enthäutet, in Streifen geschnitten<br>\r\n4  \tTomate(n), geschält und gewürfelt<br>\r\n1 Zehe/n \tKnoblauch, gepresst<br>\r\n100 ml \tWein, rot<br>\r\n  \tsaure Sahne <br>\r\n</b>\r\n<br><br><br>\r\nDie Zwiebel schälen und in Würfel schneiden. Das Fleisch in kleine Würfel schneiden und dabei alle Sehnen und Häutchen entfernen. Das Schmalz im Topf zerlassen und die Zwiebelwürfel darin von allen Seiten goldbraun anbraten. Die Fleischwürfel zugeben und 5 Min. unter ständigem Umwenden im Fett rösten.\r\nDas Paprikapulver, Kümmel, Majoran und das Salz zugeben, mit der Fleischbrühe auffüllen und alles 1 Std. zugedeckt bei milder Hitze garen. Die Kartoffelwürfel, die Paprikastreifen und die Tomatenwürfel mit dem Knoblauch in die Suppe rühren und weitere\r\n25 Min. kochen lassen. Die Suppe vom Herd nehmen und den Rotwein darunter rühren. Mit einem Klecks saurer Sahne servieren.	30	90	2013-12-10 14:44:59.541
3	Feine Linsensuppe	Linsensuppe mit Gem&uuml;se	<b>\r\n200 g \tLinsen (braune Champagne-Linsen)<br>\r\n300 g \tKartoffel(n)<br>\r\n100 g \tMöhre(n)<br>\r\n100 g \tKnollensellerie<br>\r\n100 g \tLauch<br>\r\n500 ml \tGemüsebrühe<br>\r\n500 ml \tRinderbrühe<br>\r\n1 EL \tButter<br>\r\n3 EL \tBalsamico bianco<br>\r\n  \tPetersilie, glatte oder Schnittlauch <br></b>\r\n<br><br><br>\r\n Möhre, Sellerie und Lauch in klitzekleine Würfel schneiden. Kartoffeln in Würfel mit einer Kantenlänge nicht über 5 mm schneiden.<br>\r\nLinsen waschen, abtropfen lassen und mit der Gemüsebrühe 30 Minuten köcheln lassen.<br>\r\n<br>\r\nIn einem zweiten Topf die Butter schmelzen und das Gemüse mit den Kartoffeln kurz anschwitzen. Mit der Rinderbrühe ablöschen und 5 Minuten köcheln lassen. Die Linsen dazugeben und alles gut mischen. Mit dem Essig abschmecken.<br>\r\n<br>\r\nPetersilie oder Schnittlauch fein hacken und die gefüllten Teller damit garnieren.<br>\r\n<br>\r\nDies ist eine feine Variante für den Wochenanfang, wenn man am Wochenende viel Fleisch verzehrt hat.<br>\r\n<br>\r\nDeftiger, aber auch kalorienreicher wird die Suppe durch Zugabe von klein geschnittenem Bauchspeck oder geräucherten Mettenden.<br>\r\n\t\t\t<br>	50	20	2013-12-10 14:51:57.149
4	Mokka-Cupcakes	schokoladiges Backvergn&uuml;gen	<b>\r\nFür den Teig:<br>\r\n250 g \tMehl<br>\r\n50 g \tKakaopulver<br>\r\n50 g \tZucker, brauner<br>\r\n100 g \tZucker<br>\r\n1 EL \tBackpulver<br>\r\n5 EL \tKaffeepulver, (Espressopulver), instant<br>\r\n1/2 TL \tSalz<br>\r\n100 g \tButter<br>\r\n250 g \tsaure Sahne<br>\r\n200 g \tSahne<br>\r\n2  \tEi(er)<br>\r\n150 g \tKuvertüre, (Zartbitterkuvertüre), gehackt<br>\r\n<br>\r\n  \tFür die Creme:<br>\r\n400 g \tPuderzucker<br>\r\n250 g \tKuvertüre, (Zartbitterkuvertüre)<br>\r\n125 g \tButter<br>\r\n80 g \tSahne, bei Bedarf mehr<br>\r\n etwas \tSalz<br>\r\n<br>\r\n  \tFür die Dekoration: (optional)<br>\r\n etwas \tKakaopulver<br>\r\n etwas \tPuderzucker<br>\r\n n. B. \tSchokolade, (Mokkabohnen) <br>\r\n</b><br><br><br>\r\nDen Ofen auf 200°C vorheizen.<br>\r\n<br>\r\nFür den Teig Mehl, Kakao, Zucker, Backpulver, Kaffeepulver und Salz in einer Schüssel mischen. Die Butter zerlassen und mit der Sahne und den Eiern cremig schlagen. Anschließend unter die trockenen Zutaten rühren. Zum Schluss die gehackte Zartbitterschokolade unterheben.<br>\r\n<br>\r\nMuffinformen zu 2/3 mit Teig füllen und 20-25 Minuten im vorgeheizten Ofen backen.<br>\r\n\r\nFür die Creme die Butter zusammen mit 200g Kuvertüre schmelzen und kurz abkühlen lassen. Die restlichen 50g ebenfalls schmelzen und anschließend unterrühren. Sahne und Salz unterrühren und in eine Schüssel mit dem Puderzucker geben. Die Masse glatt rühren und ggf. noch Sahne hinzufügen. Die Creme mit einem Spritzbeutel auf die abgekühlten Muffins auftragen und nach Belieben dekorieren. 	35	60	2013-12-10 14:56:01.419
5	Russischer Hackfleischtopf	Hackfleisch-Eintopf der einfachen Art	<b>\r\n2 große \tZwiebel(n)<br>\r\n1 EL \tÖl<br>\r\n1 EL \tButter<br>\r\n500 g \tGehacktes (Rind)<br>\r\n1 Stange/n \tPorree<br>\r\n5 EL \tTomate(n) - Püree<br>\r\n250 ml \tBrühe<br>\r\n1 EL \tSenf<br>\r\n1 TL \tPaprikapulver, mild<br>\r\n1 TL \tSalz<br>\r\n250 ml \tsaure Sahne <br>\r\n</b><br><br><br>\r\nDie gehackten Zwiebeln kurz in Öl und Butter in einem Brattopf dünsten. Dann die Hitze erhöhen, das Hackfleisch in den Topf geben und mit einer Holzgabel rühren, bis das Fleisch leicht braun ist.<br>\r\nBei schwacher Hitze den geputzten, in Streifen geschnittenen Lauch, Tomatenpüree, Bouillon, Senf und Gewürze nach Geschmack zugeben.<br>\r\nEtwa 15 Minuten bei schwacher Hitze dünsten, häufig umrühren. Die saure Sahne kurz vor dem Servieren darüber gießen. Heiß servieren mit gekochten Nudeln oder Reis.<br>\r\n<br>\r\n<b>Tipp:</b> Gut geeignet zum Einfrieren: Saure Sahne erst nach dem Auftauen und Erwärmen zugeben.<br>\r\n<br>\r\nGetränkevorschlag: Bier, Rotwein-Schorle, Joghurt-Mixgetränk 	15	30	2013-12-10 14:58:35.243
6	Gefüllte Paprika	ungarisches Rezept	<b>\r\n10  \tPaprikaschote(n) (Spitzpaprika), gelbe, je nach Größe evtl. mehr<br>\r\n500 g \tHackfleisch, gemischt<br>\r\n1  \tZwiebel(n)<br>\r\n1 Zehe/n \tKnoblauch<br>\r\n  \tSalz und Pfeffer, schwarzer aus der Mühle<br>\r\n  \tPaprikapulver<br>\r\n100 g \tReis, gekochter<br>\r\n1  \tEi(er)<br>\r\n1 kl. Dose/n \tTomatenmark<br>\r\n500 ml \tGemüsebrühe<br>\r\n etwas \tZucker<br>\r\n1 EL \tButter<br>\r\n1 EL \tMehl <br>\r\n</b><br><br><br>\r\nAus Hackfleisch, Reis, Ei, Zwiebel und Knoblauch einen Hackfleischteig herstellen und mit den Gewürzen abschmecken. In die Paprikaschoten füllen und aus dem Rest Hackfleischbällchen formen. Die Butter in einem Topf schmelzen, das Mehl dazugeben und etwas anrösten. Mit Gemüsebrühe ablöschen, das Tomatenmark dazugeben und aufkochen lassen. Mit Salz, Pfeffer und etwas Zucker abschmecken. Die gefüllten Paprikaschoten und die Bällchen in die Soße geben und entweder auf dem Herd oder im Backofen 30-40 min schmoren lassen.<br>\r\nDazu gibt es Reis. Alternativ kann man auch Tomatenpüree statt des Tomatenmarks verwenden. Dann etwas weniger Brühe verwenden.<br>\r\nDie Mengenangaben sind natürlich etwas vage, meine Uri hat immer "nach Gefühl" gekocht. Ich habe versucht, das Rezept so gut wie möglich nachzuvollziehen!<br>	40	70	2013-12-10 15:02:21.894
7	Omas Kohlrouladen	schmeckt wie fr&uuml;her	<b>\r\n1  \tWirsing oder Weißkohl)<br>\r\n500 g \tHackfleisch, gemischt<br>\r\n1  \tZwiebel(n)<br>\r\n1  \tBrötchen, altbacken<br>\r\n1  \tEi(er)<br>\r\n100 g \tSpeck, gewürfelt<br>\r\n500 ml \tBrühe<br>\r\n200 ml \tSahne<br>\r\n  \tSalz und Pfeffer<br>\r\n1 EL \tSenf, evtl. mehr<br>\r\n  \tPaprikapulver, scharf<br>\r\n  \tMajoran <br>\r\n</b>\r\n<br><br><br>\r\nAcht schöne Blätter vom Kohl ablösen und blanchieren. In Eiswasser abschrecken und mit einem Küchentuch etwas trocknen. Den Hackfleischteig wie folgt zubereiten: hinein gehört ein Ei, ein eingeweichtes und ausgedrücktes Brötchen, 1-2 EL Senf, eine fein gewürfelte Zwiebel, ordentlich Salz, Pfeffer und scharfes Paprikapulver. Zum Schluss nach Belieben noch getrockneten Majoran hineinstreuen. Das Ganze vermengen. Kleine Häufchen auf die ausgelegten Kohlblätter verteilen, zusammenrollen und mit einem Küchengarn zusammenbinden. Die Kohlrouladen in einer hohen Pfanne anbraten, sodass sie Farbe bekommen. Dabei auch einige Speckwürfel mit auslassen. Haben die Kohlrouladen etwas Farbe angenommen, das Ganze mit gekörnter Brühe aufgießen. Zugedeckt eine halbe Stunde schmoren lassen. Zum Schluss die Rouladen herausnehmen und die Flüssigkeit mit Sahne aufgießen, etwas einkochen lassen oder evtl. leicht abbinden. Das Ganze mit wenig Salz und Pfeffer abschmecken und die Soße zu den Kohlrouladen servieren. 	50	70	2013-12-10 15:03:36.618
8	Lasagne	wie beim Italiener	<b>\r\n500 g \tHackfleisch<br>\r\n1  \tZwiebel(n)<br>\r\n2  \tKnoblauchzehe(n)<br>\r\n1 Bund \tPetersilie oder TK<br>\r\n1 EL \tTomatenmark<br>\r\n1 Dose \tTomate(n), geschälte<br>\r\n1/2 Liter \tMilch<br>\r\n30 g \tButter<br>\r\n40 g \tMehl<br>\r\n  \tSalz und Pfeffer<br>\r\n  \tOlivenöl<br>\r\n300 g \tLasagneplatte(n)<br>\r\n  \tMuskat<br>\r\n  \tWein, rot<br>\r\n  \tKäse, gerieben<br>\r\n  \tButter, in Flöckchen <br>\r\n</b><br><br><br>\r\nRagout Bolognese:<br>\r\nIn einem Topf das Olivenöl erhitzen, das Hackfleisch darin rundherum anbraten und die gehackten Zwiebeln und die Petersilie dazugeben. Knoblauchscheiben und Tomatenmark dazu rühren und mitbraten. Mit den Dosentomaten aufgießen, salzen und pfeffern. Rotwein nach Belieben beifügen. Das Ragout mindestens eine halbe Stunde lang bei geöffnetem Topf einkochen lassen.<br>\r\n<br>\r\nBechamelsauce:<br>\r\nButter in einem kleinen Topf schmelzen und das Mehl mit dem Schneebesen dazuarbeiten. Die Milch nun dazugießen und die Sauce glatt rühren. Wer zu langsam gerührt hat und Klümpchen in der Sauce findet, kann die Sauce durch ein feines Haarsieb passieren und dann weiterkochen lassen. Die Sauce sollte fast eine halbe Stunde lang auf kleiner Flamme köcheln, damit sie den Mehlgeschmack verliert. Mit Salz, Pfeffer und Zitronensaft sowie etwas Muskatnuss abschmecken.<br>\r\n<br>\r\nZubereitung der Lasagne:<br>\r\nIn einer gebutterten, feuerfesten Form etwas Ragout bolognese verteilen, eine Schicht Lasagnenudeln darauf legen, die Nudelschicht wieder mit Ragu und dann mit einer Bechamelsaucenschicht bedecken. Anschließend wieder eine Schicht Nudeln, Ragu und Bechamel. So Schicht für Schicht die Form füllen.<br>\r\nDie letzte Schicht sollte die Bechamelsauce bilden. Dick mit geriebenen Käse bestreuen, Butterflöckchen darauf setzen . Die Lasagne bei 180°C im Ofen überbacken, bis die Kruste goldbraun ist.<br>\r\n<br>\r\nDie Lasagne kann man auch gut einen Tag vorher vorbereiten und im Kühlschrank ziehen lassen!<br>\r\n<br>\r\nEmpfehlung Vorspeise: Honigmelone mit Parmaschinken<br>\r\nEmpfehlung Nachspeise: Beerenmix an Quark-Joghurt-Sahne-Creme mit brauner Zuckerkruste! <br>	60	100	2013-12-10 15:06:24.42
9	Gnocchi Auflauf	Mix aus Auflauf, Nudeln und Kl&ouml;se	<b>\r\n200 g \tSchinken, gekochter, gewürfelt<br>\r\n300 g \tChampignons, kleine aus der Dose, halbiert<br>\r\n250 g \tKirschtomate(n), möglichst fest, halbiert<br>\r\n1  \tZwiebel(n), gewürfelt<br>\r\n3  \tKnoblauchzehe(n), gepresst<br>\r\n3 EL \tÖl<br>\r\n3 EL \tTomatenmark<br>\r\n1 EL \tMehl<br>\r\n400 g \tSahne<br>\r\n1000 g \tGnocchi, (aus der Kühltheke)<br>\r\n  \tFett, für die Auflaufform<br>\r\n200 g \tMozzarella, gewürfelt<br>\r\n200 g \tKäse (Gouda), gerieben<br>\r\n1 EL \tKräuter, italienische , z.B. gefroren<br>\r\n  \tSalz und Pfeffer, nach Geschmack <br>\r\n</b>\r\n<br><br><br>\r\nDie Tomaten in 1 El heißem Öl kurz anbraten. Mit Salz und Pfeffer würzen, herausnehmen und kurz beiseite stellen.<br>\r\n2 EL Öl in der gleichen Pfanne erhitzen und die Zwiebel mit dem Knoblauch glasig dünsten.<br>\r\nDie Pilze dazugeben und anbraten. Dann den Schinken zugeben und kurz mitbraten.<br>\r\nDas Tomatenmark hineingeben und kurz anrösten, damit sich das Tomatenaroma besser entfalten kann. Das Mehl drüber streuen, kurz verrühren und anschwitzen.<br>\r\nAnschließend mit der Sahne ablöschen. Nun die Kräuter untermischen und das ganze ca. 5 Minuten leicht köcheln lassen.<br>\r\nTomatenhälften wieder zugeben und mit Salz und Pfeffer abschmecken.<br>\r\n<br>\r\nGnocchi nach Packungsanleitung garen, abtropfen und in die große gefettete Auflaufform geben. Die Tomaten-Sahne-Sauce darüber gießen.<br>\r\nNun die Mozzarella-Würfel darüber streuen, anschließend den geriebenen Gouda darüber verteilen.<br>\r\n<br>\r\nNun für 20-30 Minuten bei 200° C im vorgeheizten Ofen überbacken.<br>\r\n\r\nUm das ganze Essen kalorientechnisch zu entschärfen, bin ich auf Milch mit 1 Becher Creme leger statt Sahne und bei den Käsesorten auf Light-Produkte ausgewichen 	30	80	2013-12-10 15:10:04.667
10	Tortellini alla panna	Schinken-Sahnesauce wie beim Italiener	<b>\r\n500 g \tTortellini, aus dem Frischeregal<br>\r\n600 ml \tSahne<br>\r\n200 g \tSchinken, gekochter, gewürfelt<br>\r\n2  \tEigelb<br>\r\n4 EL \tParmesan, frisch geriebener<br>\r\n1 TL \tMuskat<br>\r\n1 TL \tSalz<br>\r\n1 EL \tButter <br>\r\n</b><br><br><br>\r\nDie Tortellinis nach Packungsanweisung kochen.<br>\r\nDen gekochten Schinken in einer tiefen Pfanne mit Butter kurz anbraten, dann 400ml von der Sahne hineingeben und auf kleiner Stufe köcheln lassen. Wenn die Tortellini gar sind, in die Pfanne zur Schinkensahne geben und weiter köcheln lassen.<br>\r\nIn der Zwischenzeit in einer kleinen Schüssel das Eigelb, den Parmesan, Muskatnuss, Salz und die restliche 200 ml Sahne verrühren, dann in die Pfanne zu den Tortellinis geben und so lange köcheln lassen, bis die Soße dickflüssig wird. Sofort servieren.<br>\r\nSehr gehaltvoll, aber der Geschmack ist fantastisch. Ab und zu kann man sich´s mal gönnen. <br>	20	30	2013-12-10 15:11:45.826
\.

