/*
 * Copyright (C) 2014  Cookbookgeeks
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.cookbookgeeks.webkochbuch.domain;

import java.io.File;
import java.io.Serializable;
import java.nio.file.Path;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * POJO that represents an image.
 * 
 * @author Nils Sommer
 *
 */
@Entity
@Table(name="images")
public class Image implements Serializable {

	private static final long serialVersionUID = 4364318268080958100L; // generated by eclipse
	
	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="my_entity_seq_gen")
	@SequenceGenerator(name="my_entity_seq_gen", sequenceName="HIBERNATE_SEQUENCE", allocationSize=1)
	private Integer id;
	
	@Column(name="path")
	private String path;
	
	@Column(name="description")
	private String description;
	
	@ManyToOne
	@JoinColumn(name="recipe_id")
	private Recipe recipe;
	
	/**
	 * Default Constructor.
	 */
	public Image() {
		
	}
	
	/**
	 * Constructor which sets the path and the description of the image.
	 * 
	 * @param path the path of the image file
	 * @param description the description of the image
	 */
	public Image(String path, String description) {
		this.path = path;
		this.description = description;
	}
	
	/**
	 * Constructor which sets the recipe, the path and the description of the image.
	 * 
	 * @param recipe the recipe the image belongs to
	 * @param path the path of the image file
	 * @param description the description of the image
	 */
	public Image(Recipe recipe, String path, String description) {
		this.recipe = recipe;
		this.path = path;
		this.description = description;
	}
	
	// ----- Getters and setters here: -----
	
	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}
	
	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the filePath
	 */
	public String getPath() {
		return path;
	}

	/**
	 * @param file Uploaded file
	 * @param uploadFolder Upload folder where file ist stored
	 */
	public void setPath(File file, File uploadFolder) {
		// Relativize path to file, depending on where the upload folder is.
		Path filePath = file.toPath();
		Path folderPath = uploadFolder.toPath();
		String relativizedPath = folderPath.relativize(filePath).toString();
		// For microsoft operating systems: Convert path separator characters with url separator characters.
		this.path = relativizedPath.replaceAll("\\\\","/");
	}

	/**
	 * @return the description
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * @param description the description to set
	 */
	public void setDescription(String description) {
		this.description = description;
	}
	
	/**
	 * @return the recipe
	 */
	public Recipe getRecipe() {
		return recipe;
	}
	
	/**
	 * @param recipe the recipe to set
	 */
	public void setRecipe(Recipe recipe) {
		this.recipe = recipe;
	}
	
	// ----- other methods -----
	
	/**
	 * @return a host relative url that can be referenced for GET requests in a view.
	 */
	public String getViewUrl() {
		return "/images/" + this.path;
	}
	
	/** {@inheritDoc} */
	public String toString() {
		return "File path: " + path + "\nDescription: " + description +
				"\nId: " + id;
	}

}
