package org.cookbookgeeks.webkochbuch.domain;

import java.io.Serializable;
import java.util.Date;

public class Rating implements Serializable {

	private static final long serialVersionUID = 908669092769766689L; // generated by eclipse
	
	private int id;
	private int recipeId;
	private int userId;
	private int rating;
	private Date creation;
	
	// ----- Getters and setters here: -----
	
	/**
	 * @return the id
	 */
	public int getId() {
		return id;
	}
	
	/**
	 * @param id the id to set
	 */
	public void setId(int id) {
		this.id = id;
	}

	/**
	 * @return the recipeId
	 */
	public int getRecipeId() {
		return recipeId;
	}

	/**
	 * @param recipeId the recipeId to set
	 */
	public void setRecipeId(int recipeId) {
		this.recipeId = recipeId;
	}

	/**
	 * @return the userId
	 */
	public int getUserId() {
		return userId;
	}

	/**
	 * @param userId the userId to set
	 */
	public void setUserId(int userId) {
		this.userId = userId;
	}

	/**
	 * @return the rating
	 */
	public int getRating() {
		return rating;
	}

	/**
	 * @param rating the rating to set
	 */
	public void setRating(int rating) {
		this.rating = rating;
	}

	/**
	 * @return the creation
	 */
	public Date getCreation() {
		return creation;
	}

	/**
	 * @param creation the creation to set
	 */
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	
	// ----- other methods -----
	
	public String toString() {
		return "Id: " + id + "\nRating: " + rating + "\nCreation: " + creation.toString();
	}

}
