package org.cookbookgeeks.webkochbuch.domain;

import java.io.Serializable;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

/**
 * POJO which represents a Recipe.
 * @author Nils Sommer
 *
 */
@Entity
@Table(name="recipes")
public class Recipe implements Serializable {

	private static final long serialVersionUID = 3239162951065313443L; // generated by eclipse
	
	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="my_entity_seq_gen")
	@SequenceGenerator(name="my_entity_seq_gen", sequenceName="HIBERNATE_SEQUENCE", allocationSize=1)
	private Integer id;
	
	@Column(name="title")
	private String title;
	
	@Column(name="description")
	private String description;
	
	@Column(name="content")
	private String content;
	
	@Column(name="preparation_endurance")
	private int preparationEndurance;
	
	@Column(name="total_endurance")
	private int totalEndurance;
	
	@Column(name="creation")
	private Date creation;
	
	/* Will be needed later.
	private List<Image> images;
	private List<Rating> ratings;
	*/
	
	// ----- Getters and setters here: -----
	
	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}
	
	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	
	/**
	 * @return the desctiption
	 */
	public String getDescription() {
		return description;
	}
	
	/**
	 * @param desctiption the desctiption to set
	 */
	public void setDescription(String desctiption) {
		this.description = desctiption;
	}
	
	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}
	
	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}
	
	/**
	 * @return the preparationEndurance
	 */
	public int getPreparationEndurance() {
		return preparationEndurance;
	}
	
	/**
	 * @param preparationEndurance the preparationEndurance to set
	 */
	public void setPreparationEndurance(int preparationEndurance) {
		this.preparationEndurance = preparationEndurance;
	}
	
	/**
	 * @return the totalEndurance
	 */
	public int getTotalEndurance() {
		return totalEndurance;
	}
	
	/**
	 * @param totalEndurance the totalEndurance to set
	 */
	public void setTotalEndurance(int totalEndurance) {
		this.totalEndurance = totalEndurance;
	}
	
	/**
	 * @return the creation
	 */
	public Date getCreation() {
		return creation;
	}
	
	/**
	 * @param creation the creation to set
	 */
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	
	// ----- other methods -----

	/**
	 * @return a short description of the object.
	 */
	public String toString() {
		return "Title: " + title + "\nDescription: " + description +
				"\nContent: " + content + "\nPreparation endurance: " +
				preparationEndurance + "\nTotal endurance: " + totalEndurance +
				"\nCreation: " + creation.toString() + "\nId: " + id;
	}

}
