/*
 * Copyright (C) 2014  Cookbookgeeks
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 * 
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
 */

package org.cookbookgeeks.webkochbuch.domain;

import java.io.Serializable;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.hibernate.search.annotations.DateBridge;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Resolution;

/**
 * POJO which represents a Recipe.
 * 
 * @author Nils Sommer
 *
 */
@Entity
@Table(name="recipes")
@Indexed
public class Recipe implements Serializable {

	private static final long serialVersionUID = 3239162951065313443L; // generated by eclipse
	
	@Id
	@Column(name="id")
	@GeneratedValue(strategy=GenerationType.SEQUENCE, generator="my_entity_seq_gen")
	@SequenceGenerator(name="my_entity_seq_gen", sequenceName="HIBERNATE_SEQUENCE", allocationSize=1)
	private Integer id;
	
	@Field
	@Column(name="title")
	private String title;
	
	@Field
	@Column(name="description")
	private String description;
	
	@Field
	@Column(name="content")
	private String content;
	
	@Field
	@Column(name="preparation_endurance")
	private int preparationEndurance;
	
	@Field
	@Column(name="total_endurance")
	private int totalEndurance;
	
	@Field
	@DateBridge(resolution=Resolution.MINUTE)
	@Column(name="creation")
	private Date creation;
	
	@OneToMany(mappedBy="recipe")
	private List<Image> images;
	
	/**
	 * Default Constructor.
	 */
	public Recipe() {
		
	}
	
	// ----- Getters and setters here: -----
	
	/**
	 * @return the id
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * @param id the id to set
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * @return the title
	 */
	public String getTitle() {
		return title;
	}
	
	/**
	 * @param title the title to set
	 */
	public void setTitle(String title) {
		this.title = title;
	}
	
	/**
	 * @return the desctiption
	 */
	public String getDescription() {
		return description;
	}
	
	/**
	 * @param desctiption the desctiption to set
	 */
	public void setDescription(String desctiption) {
		this.description = desctiption;
	}
	
	/**
	 * @return the content
	 */
	public String getContent() {
		return content;
	}
	
	/**
	 * @param content the content to set
	 */
	public void setContent(String content) {
		this.content = content;
	}
	
	/**
	 * @return the preparationEndurance
	 */
	public int getPreparationEndurance() {
		return preparationEndurance;
	}
	
	/**
	 * @param preparationEndurance the preparationEndurance to set
	 */
	public void setPreparationEndurance(int preparationEndurance) {
		this.preparationEndurance = preparationEndurance;
	}
	
	/**
	 * @return the totalEndurance
	 */
	public int getTotalEndurance() {
		return totalEndurance;
	}
	
	/**
	 * @param totalEndurance the totalEndurance to set
	 */
	public void setTotalEndurance(int totalEndurance) {
		this.totalEndurance = totalEndurance;
	}
	
	/**
	 * @return the creation
	 */
	public Date getCreation() {
		return creation;
	}
	
	/**
	 * @param creation the creation to set
	 */
	public void setCreation(Date creation) {
		this.creation = creation;
	}
	
	/**
	 * @return a list of all image object which belong to this recipe
	 */
	public List<Image> getImages() {
		return images;
	}
	
	// ----- other methods -----

	/** {@inheritDoc} */
	public String toString() {
		return "Title: " + title + "\nDescription: " + description +
				"\nContent: " + content + "\nPreparation endurance: " +
				preparationEndurance + "\nTotal endurance: " + totalEndurance +
				"\nCreation: " + creation.toString() + "\nId: " + id;
	}

}
